### ISSUE TITLE
Issues with installing package in macOS

### ISSUE THREAD

**Issue by alkat19** [duncanobrien/EWSmethods#1]
Running install.packages("EWSmethods") does not seem to work in RStudio. I get an error saying:

Warning in install.packages :
  package ‘EWSmethods’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

I have tried with R 4.3.1 and also using version 4.2.3

**Comment by duncanobrien** [comment]
`EWSmethods` is currently unavailable on CRAN, but a hotfix has been submitted, and is currently pending CRAN team review. It should therefore be available shortly.

In the meantime, the developer version of the package can still be downloaded using the following command:
`install.packages("devtools")`
`devtools::install_github("duncanobrien/EWSmethods", dependencies = TRUE)`

I will close this issue once `EWSmethods` has returned to CRAN.

**Comment by alkat19** [comment]
Thank you!

**Comment by duncanobrien** [comment]
EWSmethods v1.2.1 is now back on CRAN
